# Generated by Django 4.1.1 on 2022-09-25 01:01

from django.db import migrations, models
import students.validators


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(db_column='phone', default='Отсутствует', max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, validators=[students.validators.ValidEmailDomain('@gmail.com', '@yahoo.com')]),
        ),
    ]
