# Generated by Django 4.1.1 on 2022-09-29 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='first name', max_length=15, validators=[django.core.validators.MinLengthValidator(3, 'you entered a name shorter than 3 characters')], verbose_name='first name')),
                ('last_name', models.CharField(db_column='last name', max_length=15, validators=[django.core.validators.MinLengthValidator(3, 'you entered a last name shorter than 3 characters')], verbose_name='last name')),
                ('phone', models.CharField(db_column='phone', max_length=12, null=True, verbose_name='phone')),
            ],
            options={
                'db_table': 'teacher_table',
            },
        ),
    ]
