# Generated by Django 4.1.1 on 2022-10-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end',
        ),
        migrations.RemoveField(
            model_name='course',
            name='group',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start',
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.TextField(blank=True, max_length=15),
        ),
    ]
