# Generated by Django 4.1.1 on 2022-10-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_alter_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
