# Generated by Django 4.1.1 on 2022-10-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
