# Generated by Django 4.1.1 on 2022-10-14 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_course_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='groups',
        ),
    ]
