# Generated by Django 4.1.1 on 2022-09-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_date_of_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_description',
            field=models.TextField(blank=True, max_length=150, verbose_name='Описание группы'),
        ),
    ]
