# Generated by Django 4.1.1 on 2022-10-12 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_remove_course_end_remove_course_group_and_more'),
        ('groups', '0005_group_headman'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_group', to='Courses.course'),
        ),
    ]
