# Generated by Django 4.1.1 on 2022-10-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_salary'),
        ('groups', '0006_group_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', to='teachers.teacher'),
        ),
    ]
